import { http, createConfig, createStorage, cookieStorage } from 'wagmi';
import {
  mainnet,
  optimism,
  arbitrum,
  arbitrumNova,
  base,
  polygon,
  polygonZkEvm,
  avalanche,
  bsc,
  zkSync,
  linea,
  scroll,
  blast,
  manta,
  mode,
  zora,
  gnosis,
  celo,
  cronos,
  cronosTestnet,
  mantle,
  metis,
  taiko,
  bob,
  boba,
  worldchain,
  ink,
  lisk,
  sei,
  sonic,
  ronin,
  abstract,
  berachain,
  morph,
  apeChain,
  shape,
  gravity,
  cyber,
  redstone,
  soneium,
  xai,
  flowMainnet,
  story,
  hemi,
  zircuit,
  superseed,
  unichain,
  monad,
  hyperEvm,
  cronoszkEVM,
} from 'viem/chains';

export const supportedChains = [
  mainnet,
  optimism,
  arbitrum,
  arbitrumNova,
  base,
  polygon,
  polygonZkEvm,
  avalanche,
  bsc,
  zkSync,
  linea,
  scroll,
  blast,
  manta,
  mode,
  zora,
  gnosis,
  celo,
  cronos,
  cronosTestnet,
  cronoszkEVM,
  mantle,
  metis,
  taiko,
  bob,
  boba,
  worldchain,
  ink,
  lisk,
  sei,
  sonic,
  ronin,
  abstract,
  berachain,
  morph,
  apeChain,
  shape,
  gravity,
  cyber,
  redstone,
  soneium,
  xai,
  flowMainnet,
  story,
  hemi,
  zircuit,
  superseed,
  unichain,
  monad,
  hyperEvm,
] as const;

export const projectId = process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID || '';

// Build transports dynamically
const transports = Object.fromEntries(
  supportedChains.map((chain) => [chain.id, http()])
) as Record<number, ReturnType<typeof http>>;

// Server-safe config (no connectors - they're added client-side)
export const config = createConfig({
  chains: supportedChains,
  transports,
  multiInjectedProviderDiscovery: false, // Disable to prevent duplicate wallets
  ssr: true,
  storage: createStorage({
    storage: cookieStorage,
  }),
});