import { tool } from "ai";
import { z } from "zod";
import { uploadToWalrus } from "@barzakh/shared/lib/ai/tools/sui/walrus-tools";
import { updateUserWalrusMemoryBlobId } from "../../db/queries";
import { fetchLiveMatches } from "../../worldcup/worldcup-api";

export const createSaveWorldCupMemoryTool = (userId: string) => tool({
  description: "Save or update the user's persistent World Cup predictions, opinions, on-chain/mock bets, contradictions, and roast to Walrus Memory.",
  parameters: z.object({
    predictions: z.array(z.object({
      id: z.string(),
      type: z.string().describe("Prediction type (e.g., 'winner', 'group_top', 'match')"),
      match: z.string().describe("The team/match/group context"),
      pick: z.string().describe("Stated pick outcome"),
      timestamp: z.string().describe("ISO timestamp"),
      status: z.enum(["pending", "correct", "incorrect"]).optional().describe("Validation status against real scores"),
    })).describe("List of stated World Cup predictions"),
    opinions: z.array(z.object({
      topic: z.string().describe("Topic of opinion, e.g. Spain, France, Cristiano Ronaldo"),
      opinion: z.string().describe("User's stated perspective/rant"),
      timestamp: z.string().describe("ISO timestamp"),
    })).describe("List of stated opinions/rants about teams/players"),
    bets: z.array(z.object({
      id: z.string(),
      txHash: z.string().describe("EVM/Sui transaction hash (mock or real)"),
      market: z.string().describe("The prediction market description"),
      outcome: z.string().describe("The chosen bet outcome"),
      amount: z.string().describe("USDC or token amount"),
      timestamp: z.string().describe("ISO timestamp"),
      isMock: z.boolean(),
    })).describe("List of on-chain or mock prediction market bets"),
    contradictions: z.array(z.object({
      prediction: z.string().describe("Stated opinion pick"),
      bet: z.string().describe("Actual on-chain bet outcome"),
      description: z.string().describe("Details of the conflict"),
      timestamp: z.string().describe("ISO timestamp"),
    })).describe("Identified conflicts between what they say and what they bet"),
    roast: z.string().describe("A witty, scathing critique generated by the agent of the user's contradictory or biased predictions"),
  }),
  execute: async ({ predictions, opinions, bets, contradictions, roast }) => {
    try {
      const payload = {
        predictions,
        opinions,
        bets,
        contradictions,
        roast,
        lastUpdated: new Date().toISOString(),
      };

      const content = JSON.stringify(payload, null, 2);
      
      // Fetch user's Sui keypair for mainnet upload
      let keypair;
      try {
        const { getSuiKeypair } = await import("../../agent/sui-agent-executor");
        keypair = await getSuiKeypair(userId);
      } catch (e) {
        console.warn("[saveWorldCupMemory] Failed to get user keypair:", e);
      }

      // Upload to Walrus
      const result = await uploadToWalrus.execute({
        content,
        fileName: `worldcup-memory-${userId}.json`,
        epochs: 1, // 1 epoch is approx 14 days
        _keypair: keypair,
      } as any);

      if (!result.success || !result.blobId) {
        throw new Error(result.message || "Failed to upload to Walrus");
      }

      // Update user db entry with the latest Walrus memory blob ID
      await updateUserWalrusMemoryBlobId(userId, result.blobId);

      return {
        success: true,
        message: "Successfully synchronized World Cup memory with Walrus Protocol.",
        blobId: result.blobId,
        explorerUrl: result.explorerUrl,
        publicUrl: result.publicUrl,
        lastUpdated: payload.lastUpdated,
      };
    } catch (error: any) {
      console.error("Error saving World Cup memory:", error);
      return {
        success: false,
        message: "Failed to save World Cup memory to Walrus.",
        error: error.message || "Unknown error",
      };
    }
  },
});

export const createSimulatePredictionMarketBetTool = (userId: string) => tool({
  description: "Simulate placing a bet on a prediction market (Polymarket mock) to test the contradiction tracker.",
  parameters: z.object({
    market: z.string().describe("The prediction market, e.g. 'FIFA World Cup 2026 Winner'"),
    outcome: z.string().describe("The outcome backed, e.g. 'Spain'"),
    amount: z.string().describe("Amount of USDC, e.g. '100 USDC'"),
  }),
  execute: async ({ market, outcome, amount }) => {
    const txHash = "0x" + Array.from({ length: 64 }, () => Math.floor(Math.random() * 16).toString(16)).join("");
    return {
      success: true,
      message: `Simulated Polymarket bet of ${amount} on ${outcome} placed successfully. Transaction hash: ${txHash.slice(0, 10)}...${txHash.slice(-8)}.`,
      bet: {
        id: Math.random().toString(36).substring(2, 11),
        txHash,
        market,
        outcome,
        amount,
        timestamp: new Date().toISOString(),
        isMock: true,
      }
    };
  },
});

export const createClearWorldCupMemoryTool = (userId: string) => tool({
  description: "Clear or reset the user's persistent World Cup predictions, opinions, on-chain bets, contradictions, and roast from Walrus. Use this when the user explicitly requests to reset, clear, delete, or wipe their memory/profile.",
  parameters: z.object({}),
  execute: async () => {
    try {
      await updateUserWalrusMemoryBlobId(userId, null as any);
      return {
        success: true,
        message: "Successfully reset persistent World Cup memory in the database. The user's memory profile has been cleared.",
      };
    } catch (error: any) {
      console.error("Error clearing World Cup memory:", error);
      return {
        success: false,
        message: "Failed to clear World Cup memory.",
        error: error.message || "Unknown error",
      };
    }
  },
});

export const createGetLiveWorldCupMatchesTool = () => tool({
  description: "Query the actual FIFA World Cup 2026 matches, schedules, scores, and status (e.g. check if a match is finished, check the scoreline).",
  parameters: z.object({
    teamName: z.string().optional().describe("Optional team name to filter matches for, e.g. 'Mexico', 'France'"),
    finished: z.boolean().optional().describe("Optional filter to return only finished matches (true) or upcoming/live matches (false)"),
  }),
  execute: async ({ teamName, finished }) => {
    try {
      let matches = await fetchLiveMatches();
      
      if (teamName) {
        const lowerName = teamName.toLowerCase();
        matches = matches.filter(m => 
          (m.home_team_name_en || "").toLowerCase().includes(lowerName) || 
          (m.away_team_name_en || "").toLowerCase().includes(lowerName)
        );
      }
      
      if (finished !== undefined) {
        const finishedStr = finished ? "TRUE" : "FALSE";
        matches = matches.filter(m => m.finished === finishedStr);
      }
      
      return {
        success: true,
        matches: matches.slice(0, 15), // Limit to top 15 relevant matches
        total: matches.length,
      };
    } catch (error: any) {
      console.error("Error fetching live matches in tool:", error);
      return {
        success: false,
        message: "Failed to fetch live World Cup match data.",
        error: error.message || "Unknown error",
      };
    }
  },
});


